# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git clone "https://$ANDY_LOGIN_INFO@github.com/andycarson182/testManuelito.git"
      env:
        ANDY_LOGIN_INFO: ${{ secrets.ANDY_LOGIN_INFO }}
    - run: npm install -g newman 
    - run: newman run testManuelito/CI-CD.postman_collection.json -e testManuelito/Test_environment.json
